### ISSUE TITLE
NPE in OcrActivity

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nelenkov/wwwjdic#16]
```
OcrActivity may fail with a NPE if it is killed and restarted while cropping.

Cf. 
java.lang.RuntimeException: Unable to resume activity 
{org.nick.wwwjdic/org.nick.wwwjdic.ocr.OcrActivity}: 
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, 
request=1, result=0, data=null} to activity 
{org.nick.wwwjdic/org.nick.wwwjdic.ocr.OcrActivity}: 
java.lang.NullPointerException
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2950)
  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2965)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
  at android.app.ActivityThread.access$2200(ActivityThread.java:119)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:123)
  at android.app.ActivityThread.main(ActivityThread.java:4363)
  at java.lang.reflect.Method.invokeNative(Method.java:-2)
  at java.lang.reflect.Method.invoke(Method.java:521)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
  at dalvik.system.NativeStart.main(NativeStart.java:-2)
Caused by: java.lang.RuntimeException: Failure delivering result 
ResultInfo{who=null, request=1, result=0, data=null} to activity 
{org.nick.wwwjdic/org.nick.wwwjdic.ocr.OcrActivity}: 
java.lang.NullPointerException
  at android.app.ActivityThread.deliverResults(ActivityThread.java:3329)
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2934)
  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2965)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
  at android.app.ActivityThread.access$2200(ActivityThread.java:119)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:123)
  at android.app.ActivityThread.main(ActivityThread.java:4363)
  at java.lang.reflect.Method.invokeNative(Method.java:-2)
  at java.lang.reflect.Method.invoke(Method.java:521)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
  at dalvik.system.NativeStart.main(NativeStart.java:-2)
Caused by: java.lang.NullPointerException: 
  at org.nick.wwwjdic.ocr.OcrActivity.onActivityResult(OcrActivity.java:311)
  at android.app.Activity.dispatchActivityResult(Activity.java:3828)
  at android.app.ActivityThread.deliverResults(ActivityThread.java:3325)
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2934)
  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2965)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
  at android.app.ActivityThread.access$2200(ActivityThread.java:119)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:123)
  at android.app.ActivityThread.main(ActivityThread.java:4363)
  at java.lang.reflect.Method.invokeNative(Method.java:-2)
  at java.lang.reflect.Method.invoke(Method.java:521)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
  at dalvik.system.NativeStart.main(NativeStart.java:-2)


```

Original issue reported on code.google.com by `nikolay....@gmail.com` on 21 Jul 2010 at 2:02

**Comment by GoogleCodeExporter** [comment]
```
should be fixed...
```

Original comment by `nikolay....@gmail.com` on 23 Jul 2010 at 9:56
- Changed state: **Fixed**
