### ISSUE TITLE
FC if back is pressed while taking a picture

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nelenkov/wwwjdic#35]
```
Camera gets released before takePicture(). Cf.

java.lang.RuntimeException: Method called after release()
at android.hardware.Camera.native_takePicture(Native Method)
at android.hardware.Camera.takePicture(Camera.java:681)
at android.hardware.Camera.takePicture(Camera.java:645)
at org.nick.wwwjdic.ocr.OcrActivity.autoFocus(OcrActivity.java:172)
at 
org.nick.wwwjdic.ocr.OcrActivity$OcrHandler.handleMessage(OcrActivity.java:213)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

```

Original issue reported on code.google.com by `nikolay....@gmail.com` on 19 Jan 2011 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
fixed in 1.62
```

Original comment by `nikolay....@gmail.com` on 2 Feb 2011 at 3:44
- Changed state: **Fixed**
