### ISSUE TITLE
NPE if speech button pressed before TTS is initialized

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nelenkov/wwwjdic#42]
```
java.lang.NullPointerException
at org.nick.wwwjdic.DetailActivity$1.onClick(DetailActivity.java:185)
at android.view.View.performClick(View.java:2534)
at android.view.View$PerformClick.run(View.java:9210)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:3652)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)

```

Original issue reported on code.google.com by `nikolay....@gmail.com` on 11 May 2011 at 1:06

**Comment by GoogleCodeExporter** [comment]
```
fixed in 1.8.1
```

Original comment by `nikolay....@gmail.com` on 15 May 2011 at 2:44
- Changed state: **Fixed**
