### ISSUE TITLE
Some buggy ROMs don't seem to support  the CHECK_TTS_DATA action

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nelenkov/wwwjdic#50]
```
ACRA log:

Caused by: android.content.ActivityNotFoundException: No Activity found to 
handle Intent { act=android.speech.tts.engine.CHECK_TTS_DATA }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1408)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1378)
    at android.app.Activity.startActivityForResult(Activity.java:2817)
    at org.nick.wwwjdic.DetailActivity.checkTtsAvailability(DetailActivity.java:201)
    at org.nick.wwwjdic.KanjiEntryDetail.onCreate(KanjiEntryDetail.java:45)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)

Check if action is available before calling?

```

Original issue reported on code.google.com by `nikolay....@gmail.com` on 28 Jun 2011 at 1:14

**Comment by GoogleCodeExporter** [comment]
```
fixed in 1.8.4
```

Original comment by `nikolay....@gmail.com` on 30 Jun 2011 at 3:28
- Changed state: **Fixed**
