### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nelenkov/wwwjdic#69]
```
One error. At version code 2250, building from 2.0 branch in wwwjdic-app: 
home/gerry/org.nick.wwwjdic/wwwjdic-app/gen/org/nick/wwwjdic/R.java:55: 
unmappable character for encoding Shift_JIS
    [javac]  item>2蛻�/item


I had to use the latest support jar and drop in flurry.
```

Original issue reported on code.google.com by `david8bl...@gmail.com` on 21 Jan 2013 at 1:14

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Thanks for your interest :)

You need to set the project encoding to UTF-8, because some files include 
string arrays with kanji. In Eclipse: right click project, select 'Properties', 
go to 'Resource'->'Text file encoding'. 
```

Original comment by `nikolay....@gmail.com` on 21 Jan 2013 at 1:44

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Now I get unexpected top-level-exception. There must be a duplication to do 
with support jar; but I get errors if I leave it out.
```

Original comment by `david8bl...@gmail.com` on 21 Jan 2013 at 5:28

**Comment by GoogleCodeExporter** [comment]
```
in /src/org/nick/wwwjdic/DictionaryFragment.java
```

Original comment by `david8bl...@gmail.com` on 21 Jan 2013 at 5:32

**Comment by GoogleCodeExporter** [comment]
```
I fixed it : I didn't have the jar named exactly android-support-v4.jar. I 
would like to distribute apks via f-droid.org, which is a market for free 
software built from source. We check for new versions via the Google Play 
automatically and then go and build them (if we can). We have to remove 
flurryagent though and replace it with a dummy because it isn't FOSS. We 
appreciate donation urls if you have them, please.
```

Original comment by `david8bl...@gmail.com` on 21 Jan 2013 at 6:34

**Comment by GoogleCodeExporter** [comment]
```
I have to provide real build instructions, but in short (Eclipse): 

1. You need to use a recent snapshot of ActionBarSherlock's dev branch and add 
it as a library project dependency). 
2. You need to copy the latest support library jar in ActionBarSherlock's libs/ 
directory. It will be automatically picked up so no need to add it to the 
Wwwwjdic project. 
3. Flurry calls should be confined to Analytics.java so either comment them out 
or place a dummy jar that has com.flurry.android.FlurryAgent with related 
methods. 


As for distribution, I am no against it, but how well do you test these things? 
I try to test on a few different devices and Android versions before releasing. 
I don't have a donate URL, only a donate app in Google Play.

BTW, I haven't used the And build for ages, it might be totally broken. 

```

Original comment by `nikolay....@gmail.com` on 22 Jan 2013 at 1:10

**Comment by GoogleCodeExporter** [comment]
```
The app builds successfully, though I used ABS at tag 4.2.0. We don't worry 
about testing much: frankly, zero developers say which subproject commits to 
use unless they use submodules, so I just use a tag close to the release time. 
I would install the first build on two phones and a tablet and hope that 
problems are reported thereafter. Of course, there is danger and I am not even 
a programmer, but the metadata can be inspected by anybody. We believe the 
value in reproducibility outweighs those dangers.
```

Original comment by `david8bl...@gmail.com` on 22 Jan 2013 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
So the app does crash for me. I don't know if it's the flurry replacement or 
not.


-------- beginning of /dev/log/system
W/InputManagerService(  204): Window already focused, ignoring focus gain of: 
com.android.internal.view.IInputMethodClient$Stub$Proxy@40728ce8
--------- beginning of /dev/log/main
D/dalvikvm( 1867): GC_CONCURRENT freed 223K, 46% free 3280K/6023K, external 
0K/0K, paused 11ms+11ms
I/ActivityManager(  204): Starting: Intent { act=android.intent.action.MAIN 
cat=[android.intent.category.LAUNCHER] flg=0x10100000 
cmp=org.nick.wwwjdic/.Wwwjdic } from pid 204
I/ActivityManager(  204): Start proc org.nick.wwwjdic for activity 
org.nick.wwwjdic/.Wwwjdic: pid=1887 uid=10053 gids={3003, 1006, 1015}
E/Sensors (  204): light: 640 lux
W/InputManagerService(  204): Window already focused, ignoring focus gain of: 
com.android.internal.view.IInputMethodClient$Stub$Proxy@40540be8
D/dalvikvm(  157): GC_EXPLICIT freed 12K, 51% free 2670K/5379K, external 0K/0K, 
paused 285ms
D/dalvikvm(  157): GC_EXPLICIT freed <1K, 51% free 2670K/5379K, external 0K/0K, 
paused 121ms
D/dalvikvm(  157): GC_EXPLICIT freed <1K, 51% free 2670K/5379K, external 0K/0K, 
paused 124ms
I/ActivityThread( 1887): Pub org.nick.wwwjdic.SearchSuggestionProvider: 
org.nick.wwwjdic.SearchSuggestionProvider
D/AndroidRuntime( 1887): Shutting down VM
W/dalvikvm( 1887): threadid=1: thread exiting with uncaught exception 
(group=0x40018560)
E/AndroidRuntime( 1887): FATAL EXCEPTION: main
E/AndroidRuntime( 1887): java.lang.RuntimeException: Unable to create 
application org.nick.wwwjdic.WwwjdicApplication: java.lang.RuntimeException: 
java.io.FileNotFoundException: keys
E/AndroidRuntime( 1887):    at 
android.app.ActivityThread.handleBindApplication(ActivityThread.java:3427)
E/AndroidRuntime( 1887):    at 
android.app.ActivityThread.access$2200(ActivityThread.java:123)
E/AndroidRuntime( 1887):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:977)
E/AndroidRuntime( 1887):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1887):    at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 1887):    at 
android.app.ActivityThread.main(ActivityThread.java:3835)
E/AndroidRuntime( 1887):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime( 1887):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 1887):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/AndroidRuntime( 1887):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
E/AndroidRuntime( 1887):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1887): Caused by: java.lang.RuntimeException: 
java.io.FileNotFoundException: keys
E/AndroidRuntime( 1887):    at 
org.nick.wwwjdic.WwwjdicApplication.readKey(WwwjdicApplication.java:294)
E/AndroidRuntime( 1887):    at 
org.nick.wwwjdic.WwwjdicApplication.onCreate(WwwjdicApplication.java:76)
E/AndroidRuntime( 1887):    at 
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
E/AndroidRuntime( 1887):    at 
android.app.ActivityThread.handleBindApplication(ActivityThread.java:3424)
E/AndroidRuntime( 1887):    ... 10 more
E/AndroidRuntime( 1887): Caused by: java.io.FileNotFoundException: keys
E/AndroidRuntime( 1887):    at android.content.res.AssetManager.openAsset(Native 
Method)
E/AndroidRuntime( 1887):    at 
android.content.res.AssetManager.open(AssetManager.java:337)
E/AndroidRuntime( 1887):    at 
android.content.res.AssetManager.open(AssetManager.java:311)
E/AndroidRuntime( 1887):    at 
org.nick.wwwjdic.WwwjdicApplication.readKey(WwwjdicApplication.java:290)
E/AndroidRuntime( 1887):    ... 13 more
W/ActivityManager(  204):   Force finishing activity org.nick.wwwjdic/.Wwwjdic
W/ActivityManager(  204):   Force finishing activity 
org.jtb.alogcat/.LogActivity
W/ActivityManager(  204): Activity pause timeout for HistoryRecord{40763910 
org.nick.wwwjdic/.Wwwjdic}
D/FDroid  ( 1843): Getting application details for org.jtb.alogcat
D/FDroid  ( 1843): Reading installed packages
E/Sensors (  204): light: 320 lux
I/Process ( 1887): Sending signal. PID: 1887 SIG: 9
I/ActivityManager(  204): Process org.nick.wwwjdic (pid 1887) has died.
D/dalvikvm(  204): JIT code cache reset in 5 ms (524268 bytes 8/0)
D/dalvikvm(  204): GC_CONCURRENT freed 613K, 43% free 5458K/9415K, external 
719K/920K, paused 11ms+18ms
I/dalvikvm( 1843): Jit: resizing JitTable from 1024 to 2048
D/dalvikvm( 1843): GC_CONCURRENT freed 219K, 35% free 5176K/7879K, external 
54K/521K, paused 6ms+7ms
I/ActivityManager(  204): Starting: Intent { act=android.intent.action.MAIN 
cat=[android.intent.category.LAUNCHER] flg=0x10100000 pkg=org.jtb.alogcat 
cmp=org.jtb.alogcat/.LogActivity } from pid 204
E/Sensors (  204): light: 225 lux
D/FDroid  ( 1843): Read app data from database  (took 2249 ms)
E/Sensors (  204): light: 320 lux
W/ActivityManager(  204): Activity pause timeout for HistoryRecord{406b20d8 
org.fdroid.fdroid/.AppDetails}
D/ViewConsistency( 1867): AbsListView android.widget.ListView@405eb078 enabled= 
false
D/ViewConsistency( 1867): AbsListView android.widget.ListView@405eb078 enabled= 
false
I/ActivityManager(  204): Displayed org.jtb.alogcat/.LogActivity: +384ms (total 
+6s709ms)

```

Original comment by `david8bl...@gmail.com` on 22 Jan 2013 at 11:36

**Comment by GoogleCodeExporter** [comment]
```
Ah, there's that :) I probably need to make this part more forgiving. I store 
the Flurry API key in a 'keys' text file in the asset folder. It is loaded on 
startup and you get an error because it doesn't exist. Put a dummy 'keys' file 
/assets and rebuild, it should work. 
```

Original comment by `nikolay....@gmail.com` on 22 Jan 2013 at 3:11

**Comment by GoogleCodeExporter** [comment]
```
Also update to get the radical file I just committed (also in assets). 
```

Original comment by `nikolay....@gmail.com` on 22 Jan 2013 at 3:24

**Comment by GoogleCodeExporter** [comment]
```
Excellent! That will go in , in the next few days. The metadata is at 
http://gitorious.org/f-droid/fdroiddata/trees/master. Please contact us if you 
want any of it changed.
```

Original comment by `david8bl...@gmail.com` on 22 Jan 2013 at 3:37

**Comment by GoogleCodeExporter** [comment]
```
done
```

Original comment by `david8bl...@gmail.com` on 22 Jan 2013 at 3:40

**Comment by GoogleCodeExporter** [comment]
```
Looks good. Just a few comments: 

 * The Science & Education category is probably a better fit than Office
 * Since Flurry has been removed, there is not tracking 
 * Does non-Free refer to price? If so, Kanji Recognizer is a free app. The N2 TTS engine is also free (Japan only, unfortunately)
```

Original comment by `nikolay....@gmail.com` on 23 Jan 2013 at 4:24

**Comment by GoogleCodeExporter** [comment]
```
The tracking refers to the crash reporting being on by default. The non-free is 
in the sense of free as in freedom. I nearly applied the nonfree network 
service anti-feature, but you use weocr which is apache licensed. It would be 
nice though, to offer a choice of URL to use one's own OCR server. 

I would like to point out too that the source code should be more explicit 
about the license of the app, and advertise any notices regarding the acra and 
opencsv, which you are obliged to publish according to their licence.
```

Original comment by `david8bl...@gmail.com` on 24 Jan 2013 at 3:20

**Comment by GoogleCodeExporter** [comment]
```
I see. I wouldn't exactly call crash reporting and anti-feature, but if that is 
your policy... As for weOCR, very few servers support Japanese, so adding your 
own server will likely just break things. 

You are right license notices though, I will look into adding the files. 
```

Original comment by `nikolay....@gmail.com` on 24 Jan 2013 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
 We are consistent about default crash reporting, though not about non-free addons. At the moment it mainly applies to apps that promote premium versions, so I think I'll remove that anti-feature.
```

Original comment by `david8bl...@gmail.com` on 24 Jan 2013 at 5:32

**Comment by GoogleCodeExporter** [comment]
```
Thanks!
```

Original comment by `nikolay....@gmail.com` on 24 Jan 2013 at 11:38

**Comment by GoogleCodeExporter** [comment]
Original comment by `nikolay....@gmail.com` on 25 Jan 2013 at 1:44
- Changed state: **Fixed**
